version: "3.9"
services:
  Jenkins:
    image: test-jenkins
    build:
      context: Jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

###################################
#			ADD FILE .ENV		  #
###################################

    env_file:
      - .env

#######################################
#			SET VOLUME JENKINS		  #
#######################################

    volumes:
      - jenkins_local:/var/jenkins_local
      
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
      volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
volumes:
    jenkins_local:
    data:
